---
# get provisioned karbon cluster kubeconfig
- name: Get provisioned Karbon cluster kubeconfig
  uri:
    url: "{{ prism_central_karbon_api }}/v1/k8s/clusters/{{ karbon_cluster_name }}/kubeconfig"
    method: GET
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ session_cookie }}"
    status_code: 200
  register: karbon_cluster_kubeconfig
  when: >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" )


- name: Stash the Karbon cluster kubeconfig
  set_fact:
    karbon_kubeconfig: "{{ karbon_kubeconfig|default([]) + [ {'name': {{ karbon_cluster_name }}, 'kubeconfig': karbon_cluster_kubeconfig.json.kube_config } ] }}"


# debug template
- name: Debug | Print Karbon cluster kubeconfig
  debug:
    msg: "{{ karbon_cluster_kubeconfig.json.kube_config }}"
  when:  >
    ( wait ) and
    ( karbon_create_status.json.status == "kSucceeded" ) and
    global_debug
